FROM ocaml/opam:alpine-ocaml-4.12

# Make sure the sources are all there
COPY . /pasv
WORKDIR /pasv

RUN sudo apk add linux-headers

# Build the deps needed to build pasv
RUN eval $(opam env) && \
    opam update -y

RUN eval $(opam env) && \
    opam install . -y --deps-only # --with-doc --with-test
