#!/bin/bash

bin_dir="$1"
num_threads="$2"
references="$3"
queries="$4"
start="$5"
end="$6"
posns="${@:7:99}"

cmd="$bin_dir/split_seqs $num_threads $queries"
#"$bin_dir"/split_seqs "$num_threads" "$queries"
$cmd

parallel "$bin_dir/group_seqs $references {} $start $end $posns" ::: "$queries".split_*
#parallel "$bin_dir"/group_seqs "$references" "$queries" "$start" "$end" "$posns" ::: "$queries".split_*

#echo $bin_dir/partition_seqs $queries $queries.split_*.seq_groups
"$bin_dir"/partition_seqs "$queries" "$queries".split_*.seq_groups
