name: Build and Test Static

on:
  push:
    branches:
      - "main"
      - "staging"
      - "ci_build_test_static"
  pull_request:
    branches:
      - "*"

env:
  PROGRAM_NAME: pasv

jobs:
  build_and_test_static:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mooreryan/pasv_build_and_test_alpine:eae9a79

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - run: opam exec -- make test_static
      - run: opam exec -- make build_static

      - name: Upload the build artifact
        uses: actions/upload-artifact@v2
        with:
          name: alpine-4.14.1-static-${{ env.PROGRAM_NAME }}
          path: _build/install/default/bin/${{ env.PROGRAM_NAME }}
