name: Build and Test Static

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  PROGRAM_NAME: pasv

jobs:
  build_and_test_static:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mooreryan/pasv_build_and_test_alpine:553acf9

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - run: OCAMLPARAM=_,ccopt=-static opam exec -- make test
      - run: OCAMLPARAM=_,ccopt=-static opam exec -- make build_release

      - name: Upload the build artifact
        uses: actions/upload-artifact@v2
        with:
          name: alpine-4.12.0-static-${{ env.PROGRAM_NAME }}
          path: _build/install/default/bin/${{ env.PROGRAM_NAME }}
