name: Build static

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  release:
    types:
      - '*'

jobs:
  build_static:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mooreryan/pasv_build_and_test_alpine:553acf9

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - run: opam exec -- ./_scripts/build_helpers/build_and_test_static

      - name: Upload the build artifact
        uses: actions/upload-artifact@v2
        with:
          name: alpine-4.12.0-static-pasv
          path: _build/install/default/bin/pasv
